/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("java-library")
}

dependencies {
    api(project(":game"))
}

application {
    // Define the main class for the application.
    mainClass = "feup.cpd.server.App";
}
