/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
    id("java-library")
}

java{
    toolchain{
        languageVersion = JavaLanguageVersion.of(21)
    }
}


tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "feup.cpd.server.App"
    }
}

dependencies {
    api(project(":game"))
}

application {
    // Define the main class for the application.
    mainClass = "feup.cpd.server.App";
}


tasks {
    val delete = register<Delete>("DeleteSERFiles") {
        delete(fileTree(".") {
            include("**/*.ser")
        })
    }


    val run = named<JavaExec>("run") {
        standardInput = System.`in`
    }

    run.configure {
        dependsOn(delete)
    }

}