/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package feup.cpd.client;

import feup.cpd.game.Game;
import feup.cpd.protocol.MessageReader;
import feup.cpd.protocol.ProtocolFacade;
import feup.cpd.protocol.exceptions.InvalidMessage;
import feup.cpd.protocol.models.*;
import feup.cpd.protocol.models.enums.QueueType;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.InetSocketAddress;
import java.nio.channels.SocketChannel;
import java.util.Scanner;

public class App {
    public static void main(String[] args) throws IOException, InvalidMessage {
        //change this to be compatible with docker
        SocketChannel clientChannel = SocketChannel.open(new InetSocketAddress("localhost", 4206));
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter username: ");
        String username = scanner.nextLine();

        System.out.print("Enter password: ");
        String password = scanner.nextLine();


        ProtocolModel protocolModel =
                ProtocolFacade.sendModelAndReceiveResponse(
                        clientChannel, new LoginRequest(username, password));

        assert protocolModel != null;
        System.out.println(((Status) protocolModel).message);

        QueueToken queueToken =
                (QueueToken) ProtocolFacade.sendModelAndReceiveResponse(
                        clientChannel, new QueueJoin(QueueType.NORMAL));

        System.out.println(queueToken.uuid);
    }
}
